### ISSUE TITLE
Deprecated function is used, and causing warning messages.

### ISSUE THREAD

**Issue by suckgeun** [udacity/machine-learning#142]
At machine-learning/projects/smartcab/visuals.py file, 
pd.ralling_mean() is used, and it is causing unnecessary warning. 
Warning should be suppressed or the function should be replaced with other function.

>visuals.py:74: FutureWarning: pd.rolling_mean is deprecated for Series and will be removed in a future version, replace with 
Series.rolling(window=10,center=False).mean()
data['average_reward'] = pd.rolling_mean(data['net_reward'] / (data['initial_deadline'] - data['final_deadline']), 10)
visuals.py:75: FutureWarning: pd.rolling_mean is deprecated for Series and will be removed in a future version, replace with 
Series.rolling(window=10,center=False).mean()
data['reliability_rate'] = pd.rolling_mean(data['success']*100, 10) # compute avg. net reward with window=10
visuals.py:78: FutureWarning: pd.rolling_mean is deprecated for Series and will be removed in a future version, replace with 
Series.rolling(window=10,center=False).mean()
(data['initial_deadline'] - data['final_deadline']), 10)
visuals.py:80: FutureWarning: pd.rolling_mean is deprecated for Series and will be removed in a future version, replace with 
Series.rolling(window=10,center=False).mean()
(data['initial_deadline'] - data['final_deadline']), 10)
visuals.py:82: FutureWarning: pd.rolling_mean is deprecated for Series and will be removed in a future version, replace with 
Series.rolling(window=10,center=False).mean()
(data['initial_deadline'] - data['final_deadline']), 10)
visuals.py:84: FutureWarning: pd.rolling_mean is deprecated for Series and will be removed in a future version, replace with 
Series.rolling(window=10,center=False).mean()
(data['initial_deadline'] - data['final_deadline']), 10)
visuals.py:86: FutureWarning: pd.rolling_mean is deprecated for Series and will be removed in a future version, replace with 
Series.rolling(window=10,center=False).mean()
(data['initial_deadline'] - data['final_deadline']), 10)

**Comment by jared-weed** [comment]
Hi,

The function `rolling` comes from `pandas` v0.19. Anaconda still uses v0.18 where this function is unsupported.

**Comment by jared-weed** [comment]
Fixed with #150
