### ISSUE TITLE
Typo for Epsilon in Simulator

### ISSUE THREAD

**Issue by SamWhitehill** [udacity/machine-learning#147]
In the simulator line 298 reads "    print "espilon = {:.4f}; alpha = {:.4f}".format(a.epsilon, a.alpha)"
but  it should be:
    print "epsilon = {:.4f}; alpha = {:.4f}".format(a.epsilon, a.alpha)"

Epsilon was misspelled.

**Comment by adarsh0806** [comment]
Typo fixed.
