### ISSUE TITLE
Comment bug in agent.py

### ISSUE THREAD

**Issue by harrylippy** [udacity/machine-learning#171]
In the LearningAgent class, the following comment block exists in two places (in build_state, lines 59-61, and in createQ, lines 88-90):

        # When learning, check if the state is in the Q-table
        #   If it is not, create a dictionary in the Q-table for the current 'state'
        #   For each action, set the Q-value for the state-action pair to 0

I believe this comment is correct in createQ method, but not the build_state method.  It definitely shouldn't be in both places.  We've had several students understandably confused by this, so I promised to see if we could get it corrected in the github repository.

**Comment by harrylippy** [comment]
NOTE:  I submitted this issue to machine-support@udacity.com as well, but I thought it might get more visibility here.

**Comment by caramelslice** [comment]
Please fix this. It's very confusing for new learners.

**Comment by harrylippy** [comment]
Code is now fixed.
