### ISSUE TITLE
Error in argument type for function visuals.survival_stats

### ISSUE THREAD

**Issue by albertvillanova** [udacity/machine-learning#188]
In notebook titanic_survival_exploration.ipynb, there is a TypeError when calling the function visuals.survival_stats:
`TypeError: Cannot concatenate list of ['DataFrame', 'Series']`

This could be fixed by transforming outcomes from pandas.Series to pandas.DataFrame by means of the function pandas.Series.to_frame():
`outcomes.to_frame()`

**Comment by xuzhe0628** [comment]
I encountered the same issue
