### ISSUE TITLE
Shuffle split needs to be updated for Sklearn 1.8 (boston housing)

### ISSUE THREAD

**Issue by Divya-Viswa** [udacity/machine-learning#206]
Project: boston_housing

For the Visuals.py , both ModelLearning and ModelComplexity code needs to be updated for Shufflesplit..

n_iter is no longer supported.

cv = ShuffleSplit(n_splits=10, test_size=0.2,random_state = 0)
cv.get_n_splits(X.shape[0])

**Comment by Raviteja-Ainampudi** [comment]
Hi Divya-Viswa,

I believe that depends on the sklearn what you were running on your machine.

if sklearn is 0.18.1
cv = ShuffleSplit(n_splits=10, test_size=0.2,random_state = 0) works.

if sklearn is 0.17.1
cv = ShuffleSplit(n_iter=10, test_size=0.2,random_state = 0) works.

My machine has sklearn 0.17.1, n_iter working on my PC.


Thanks,
Ravi.

**Comment by Divya-Viswa** [comment]
Thanks for writing Ravi.. Raised this because we had a new pull request where the project got updated to use Sklearn 1.8.
