### ISSUE TITLE
Spam example - maketrans 

### ISSUE THREAD

**Issue by mikelam14** [udacity/machine-learning#207]
Hi,
In the example of spam filter, the use of maketrans returns error. 
First: type object 'str' has no attribute 'maketrans' 
After i changed str to string, then: Maketrans() takes exactly 2 arguments

Following is the code in the sample. 
```
sans_punctuation_documents = []
import string

for i in lower_case_documents:
    sans_punctuation_documents.append(i.translate(str.maketrans('', '', string.punctuation)))
print(sans_punctuation_documents)
```

**Comment by adarsh0806** [comment]
This is using the definition as specified here - https://docs.python.org/3/library/stdtypes.html#str.maketrans which works in Python 3.x

**Comment by akash291418** [comment]
i'm getting the same issue .

**Comment by akash291418** [comment]
sans_punctuation_documents.append(string.translate(i, table=None, deletions=string.punctuation))
use this instant of that
