### ISSUE TITLE
Error Importing "import visuals as vs"

### ISSUE THREAD

**Issue by priyanshAgarwal** [udacity/machine-learning#209]
![capture](https://cloud.githubusercontent.com/assets/6958908/25774237/7fa85072-32a9-11e7-877a-158eacd9ef18.PNG)
Guys I am having issue running first cell. I think there is error importing the visuals.py file..!!

**Comment by Raviteja-Ainampudi** [comment]
Hi Priyansh,

As per the error, Visuals.py isn't available in PYTHONPATH.

Please upload visuals.py in Jupyter Home page. As shown in below picture.
[image: Inline image 1]


Thanks,
Ravi.

**Comment by stanna15** [comment]
Hi Ravi / Priyansh, sorry to add to this but I think I am having a related but perhaps different problem with this module. This is the output I am getting, perhaps it is having some issue within the module itself that I should change? 

![image](https://user-images.githubusercontent.com/34770544/34297714-c86e0f2a-e6e7-11e7-8488-3ab2b1053904.png)

As a side note, I tried the uploading technique (I uploaded to the titanic folder and overwrote the visuals.py that already existed using Ravi's advice) and other tries like adding a PYTHONPATH to my system environment variables with the visuals.py in there. 

Thanks so much for your help.

PS - it works when I comment the import visuals line

**Comment by kyass** [comment]
I am having the same issues as stanna15.  

Stanna15 - have you figured out the problem?

**Comment by mchez808** [comment]
I've had the same issues as stanna15 and kyass.  I haven't figured it out yet.

**Comment by mchez808** [comment]
@stanna15  @kyass  I found the reason.  In the visuals.py as well as in the Jupyter notebook, sometimes the print function appears as  `print "arg"` instead of `print("arg")` as it should.  Print must be followed by parentheses.  (Python 2 didn't require them.  Google "python 2 vs 3 print" and it's the first result.)

<img width="697" alt="screen shot 2018-01-09 at 4 36 47 pm" src="https://user-images.githubusercontent.com/30915839/34750321-5b1b39de-f55b-11e7-9f42-3186dc7692cc.png">

**Comment by girishlc** [comment]
Hi Team,

Is this issue is resolved ?

May I know the solution please, why this issue as marked as "closed"

**Comment by girishlc** [comment]
> Hi Team,
> 
> Is this issue is resolved ?
> 
> May I know the solution please, why this issue as marked as "closed"

Hey Folks,

I'm able to solve this issue, actually the code visuals.py is present in the home directory(not standard library) but while importing this (import visuals as vs) it will throw an error for importing matplotlib(dependency for this), this has to resolve by installing matplot lib.(pip install matplotlib) and make sure that you restart your kernel in the Kernel menu in the jupyter.
