### ISSUE TITLE
error: boston_housing

### ISSUE THREAD

**Issue by NavJag** [udacity/machine-learning#214]
I'm getting the following error.  Could you please let me know what is missing here?

![capture](https://cloud.githubusercontent.com/assets/28723313/26091229/fe642b36-39d7-11e7-9fc0-1b6a0eac5dea.JPG)

**Comment by gparkis** [comment]
cross_validation is no longer used with sklearn.
It is now model_selection as the submodule.

**Comment by NavJag** [comment]
i changed that to model_selection, but i get the following error

NameError                                 Traceback (most recent call last)
<ipython-input-2-6433f9254bf7> in <module>()
      5 
      6 # Import supplementary visualizations code visuals.py
----> 7 import visuals as vs
      8 

C:\Users\usnjagadis\visuals.py in <module>()
    128 
    129     # Display price range
--> 130 print "\nRange in prices: ${:,.2f}".format(max(prices) - min(prices))

NameError: name 'prices' is not defined

**Comment by gparkis** [comment]
Did you download the visuals.py to your pc? If so that file needs to be in
same directory as your notebook.
