### ISSUE TITLE
Image classification project environment instructions

### ISSUE THREAD

**Issue by excieve** [udacity/machine-learning#216]
Everywhere in the nanodegree materials (including the Deep Learning course) it's stated that the Python version being used is 2.7, however apparently image classification project relies on 3.x. There are no instructions about setting up the environment for it too. I've managed to do this on my own by trial and error but this really should be specified somewhere in the course materials so that students wouldn't waste time on trying to set up with Python 2 for it.

**Comment by adarsh0806** [comment]
Note added in readme.
