### ISSUE TITLE
Numpy and Pandas Tutorial: Some coding quiz submit answer result in import error

### ISSUE THREAD

**Issue by one-for-all** [udacity/machine-learning#241]
Submitting Answer results in import error, because it imports the wrong function.

For example, in Quiz 11, Average Bronze Medals:
```
Traceback (most recent call last):
  File "vm_main.py", line 33, in 
    import main
  File "/tmp/vmuser_bjdwrarirz/main.py", line 2, in 
    import aiMain
  File "/tmp/vmuser_bjdwrarirz/aiMain.py", line 2, in 
    from student import avg_medal_count as student_code
ImportError: cannot import name avg_medal_count
```
However, the function that is provided is named avg_bronze_medal_count

Similar problem in Quiz 14, Olympics Medal Points

**Comment by Mohamed-Anwar-Saeed** [comment]
Yes, same here...
I think this happens because the evaluation code calls a function called "avg_medal_count" for some reason. So, to solve this problem just call that function using the function you have created which is "avg_bronze_medal_count" like so:

```
def avg_medal_count():

    return avg_bronze_medal_count()
```
