### ISSUE TITLE
 print "'{}' is not a feature of the Titanic data. Did you spell something wrong?".format(key)

### ISSUE THREAD

**Issue by 43x79** [udacity/machine-learning#247]
![image](https://user-images.githubusercontent.com/30804900/29045171-8f27ff18-7b90-11e7-9b8a-7fd2a2f48bc2.png)
does anyone know why this is happening? I don't know what the warning means.

**Comment by gparkis** [comment]
It's in the visuals.py file, line 6 I think. It's referring to some
formatting that the print function is being asked to call which is not
present.

**Comment by sananand007** [comment]
I can see on the top right corner that you are using , Python-3 , 

> Do not Use Python-3 for this course , use only Python 2.7 for now as all Python code is written in Python 2.7

**Comment by micahdanger** [comment]
![screen shot 2017-10-30 at 11 04 23 pm](https://user-images.githubusercontent.com/13108715/32209688-66a2ae36-be01-11e7-9221-14110b237b4b.png)

This happens when running python2 in Jupyter also.

**Comment by vibha-1997** [comment]
The last line in visuals.py contains a print statement where format function is used in wrong manner.Just remove the single inverted comma from there i.e convert '{}' to {}
![image](https://user-images.githubusercontent.com/27447163/32995015-c4963ccc-cd94-11e7-9e74-039a2cbbf607.png)

**Comment by Athalka** [comment]
For anyone interested, if you are using Python3  just add paranthesis for print statements and it is a go.
For example in visuals.py (old):
`print "'{}' is not a feature of the Titanic data. Did you spell something wrong?".format(key)`
New code would be:
`print ("'{}' is not a feature of the Titanic data. Did you spell something wrong?".format(key))`

Replace both visuals py, and also Jupyter notebook statements for print as said and code runs.
