### ISSUE TITLE
logs folder?

### ISSUE THREAD

**Issue by ljj-ml** [udacity/machine-learning#251]
I found there is no logs folder which is required for course submission. I tried to create one in home folder but simulation did not result in any log files. Any idea to fix?

**Comment by rikeoka** [comment]
If this is for smartcab, there is a flag to set in the code to create the logs.

**Comment by ljj-ml** [comment]
I did set it as True but nothing created.

**Comment by ljj-ml** [comment]
Solved. I put the flags in the wrong place in the code. Now everything works good.
