### ISSUE TITLE
smartcab project missing folder

### ISSUE THREAD

**Issue by wonderlives** [udacity/machine-learning#257]
In the smartcab project, student is asked to set the `'log_metrics'` to `True` to record logs to `/logs/`. However, this folder is missing and students will run into error information like:

>  No such file or directory: 'logs/sim_no-learning.csv'

One quick fix is to add the `logs` folder manually. 

PS. In the README.md, it stated there is a `logs` folder but there is none.

**Comment by HappyStorm** [comment]
same here...
