### ISSUE TITLE
Error in lecture video?

### ISSUE THREAD

**Issue by parhelia** [udacity/machine-learning#259]
In Lesson 1: Deep Neural Networks, [Section 28. Neural Network Architecture](https://classroom.udacity.com/nanodegrees/nd009/parts/99115afc-e849-48cf-a580-cb22eea2ba1b/modules/777db663-2b0d-4040-9ae4-bf8c6ab8f157/lessons/21d39927-8e4f-44ba-8425-d15889ac19e2/concepts/7a42d26d-7d7e-4c76-a014-5bf8b4413179)., in the second video, [at the 1’08" mark](https://www.youtube.com/watch?v=au-Wxkr_skM&t=1m8s), he combines the weights into a more compact form. The weights from x1 are 5 and -2 and from x2 are 7 and -3. Shouldn’t the weights from x1 be 5 and 7 and from x2, -2 and -3? It seems the “inner” weights should be swapped, because when I write the equations down they make sense, but not in the form as presented in the lecture video.

[Link to thread in discussion forum.](https://discussions.udacity.com/t/error-in-lecture-video/348611)

**Comment by ronny-udacity** [comment]
At the 1'08" mark, the nodes are arranged as [x1, x2, x1, x2] from top to bottom. It is probably easier to understand the weight distribution after the nodes re-arrangements at the 1'13" mark.
