### ISSUE TITLE
finding donors `.ipynb` notebook is corrupted - doesn't load

### ISSUE THREAD

**Issue by giladgressel** [udacity/machine-learning#261]
also, a student pushed solutions into the (finding donors) section.  Also maybe other sections..
It should be rolled back
@adarsh0806

**Comment by sbetageri** [comment]
https://github.com/udacity/machine-learning/blob/master/projects/boston_housing/boston_housing.ipynb

Leaving link for brevity.

**Comment by clapollo** [comment]
Should be fixed now.
