### ISSUE TITLE
finding_donors.ipynb has erroneous diff comments in it

### ISSUE THREAD

**Issue by sgreenberg** [udacity/machine-learning#262]
Lines 1305 through 1314 are currently: 

```
   "name": "python",
   "nbconvert_exporter": "python",
<<<<<<< HEAD
   "pygments_lexer": "ipython2",
   "version": "2.7.13"
=======
   "pygments_lexer": "ipython3",
   "version": "3.6.0"
>>>>>>> 9fdeb5401039b5e0cb08048e236e1e661de673fd
  }
```

This seems to have been introduced in [commit b48b3d19654722562f8d7142a336dcecd782a28d](https://github.com/udacity/machine-learning/commit/b48b3d19654722562f8d7142a336dcecd782a28d#diff-3948450159cbc91c99e40d7788a16a4bR1305)

This results in an error message when loading the file: 

Unreadable Notebook: ~/git/machine-learning/projects/finding_donors/finding_donors.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...',)

**Comment by sgreenberg** [comment]
Also, the notebook is filled in with answers. Please see this thread on the discussions forum: 

https://discussions.udacity.com/t/the-notebook-on-udacitys-github-repo-appears-to-be-answered/350436

**Comment by clapollo** [comment]
Should be fixed now.
