### ISSUE TITLE
CharityDonorMl Visual.py error

### ISSUE THREAD

**Issue by yashgyy** [udacity/machine-learning#281]
![image](https://user-images.githubusercontent.com/14790911/30610659-805b8f08-9d9c-11e7-90b9-1ddebbbabdf8.png)

I m getting Index Error while Submitiing the Project and i don't know how to Resolve . i m using Python 3

**Comment by y3g0r** [comment]
I guess this is because project is meant to be done on python 2. Divison operation on python 2 returns integers, but on python 3 it returns floats. Float can not be used as an index.

**Comment by yashgyy** [comment]
Maybe I could try floor division of Python 3

**Comment by y3g0r** [comment]
Here is a pull request to make it possible on python 3 https://github.com/udacity/machine-learning/pull/279/files

**Comment by yashgyy** [comment]
Thnx y3g0r I will try soon as I reach home

**Comment by yashgyy** [comment]
Y3G0R thank you that solved the problem for me
