### ISSUE TITLE
Error in Learning Curves

### ISSUE THREAD

**Issue by noopur2805** [udacity/machine-learning#289]
In Lesson 8. Learning Curves, of Part 1- Machine Learning Foundations, in the ML nanodegree, According to the graphs as shown, it should be no. of training examples in x-axis instead of degree of polynomial since the polynomial degree being constant say 2 and we are increasing the training data size.

Also for the last graph in the video, shouldn’t it be degree=6 instead of 12, and I guess it should have been High Variance for the same.

**Comment by ronny-udacity** [comment]
Thanks for reporting the issue.
