### ISSUE TITLE
Naive Bayes Project

### ISSUE THREAD

**Issue by alij** [udacity/machine-learning#297]
I am at the end of the practice project where we try to predict using testing_data. Specifically:

`predictions = naive_bayes.predict(testing_data)`

I am getting a dimension mismatch error:

![image](https://user-images.githubusercontent.com/333205/32220366-4c636694-be53-11e7-8962-2327b784c8d1.png)

I have followed all the steps and I can't see anything obvious that I could be doing wrong. Could anyone please help?

Thanks
Ali

**Comment by pkkdguy** [comment]
use this
`testing_data = CountVectorizer.transform(X_test)` instead of `testing_data=CountVectorizer.fit_transform(X_test)`

I found it [here ](https://stackoverflow.com/questions/12484310/scipy-and-scikit-learn-valueerror-dimension-mismatch)
I still have a doubt on this, can someone explain!
