### ISSUE TITLE
typo in practices of naive bayes tutorial

### ISSUE THREAD

**Issue by leesper** [udacity/machine-learning#312]
in section "Step 4.1: Bayes Theorem implementation from scratch", the calculation of P(Pos):

```python
# P(Pos)
p_pos = (p_diabetes * p_pos_diabetes) + (p_no_diabetes * (1 - p_neg_no_diabetes))
print('The probability of getting a positive test result P(Pos) is: {}',format(p_pos))
```
should be:
```
print('The probability of getting a positive test result P(Pos) is: {}'.format(p_pos))
```

it is a dot, not a comma

**Comment by Sambeth** [comment]
When I see such typos I feel it could be intentional to test our knowledge of python. Especially when the same typo occurs over and over again.
