### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by NaveenAMohanan** [udacity/machine-learning#329]
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\learning_curve.py:22: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the functions are moved. This module will be removed in 0.20
  DeprecationWarning)
"Can someone upload the anaconda enviroment in which it was originally done

**Comment by ronny-udacity** [comment]
The Udacity Workspace is running on `sklearn v0.19`. If you use the newer version (>="0.20") on your local machine, the `sklearn.cross_validation` has been replaced with `sklearn.model_selection`.
