### ISSUE TITLE
plots come out very small in Charity ML

### ISSUE THREAD

**Issue by ad8700** [udacity/machine-learning#340]
When running vs.evaluate in Initial Model Evaluation cell, the command vs.evaluate(results, accuracy, fscore) creates the plots, but the plots are too small to be legible.  How do I increase the size of the plots?

![plot_vs_evaluate](https://user-images.githubusercontent.com/14060225/42486078-022a2792-83c0-11e8-806f-2e9e66eb7187.png)

**Comment by DavidMachineLearning** [comment]
You can fix that issue by changing the "figsize" parameter on the line 63 in visuals.py script.
i used figsize=(25,15)

**Comment by josiasMO** [comment]
I'm having the same issue, even after trying the solution above.

![image](https://user-images.githubusercontent.com/9166021/43372227-e8df7782-9374-11e8-9e01-0e1b5273f264.png)

**Comment by DavidMachineLearning** [comment]
Ok i found a trick to fix the issue.
In visual.py write:

    fig, ax = pl.subplots(2, 4, figsize=(11, 7))  # replace the code on line 63 with this

then delete the block "# Create patches for the legend"
and replace it with the following

    # Set additional plots invisibles
    ax[0, 3].set_visible(False)
    ax[1, 3].axis('off')

    # Create legend
    for i, learner in enumerate(results.keys()):
        pl.bar(0, 0, color=colors[i], label=learner)
    pl.legend()

![screenshot from 2018-08-02 15-44-22](https://user-images.githubusercontent.com/41441668/43587693-16d94098-966b-11e8-802f-378f38e5468a.png)

**Comment by DavidMachineLearning** [comment]
If you want to make the image bigger, you can change the "figsize" parameter.
If you have any questions, just ask :)

**Comment by josiasMO** [comment]
I still have this issue, even with the new version of the visuals.py.
Do you have idea of what could be wrong, @DavidMachineLearning ?

Thanks

![screen shot 2018-08-26 at 5 25 07 pm](https://user-images.githubusercontent.com/9166021/44632672-10903280-a955-11e8-8ef4-1a8def8be6da.png)

**Comment by DavidMachineLearning** [comment]
I don't see any issue, the visualization now is good.
Are you talking about the scores? @josiasMO

**Comment by fabio-reale** [comment]
Thanks @DavidMachineLearning, you just fixed my problem 28 days ago.

**Comment by josiasMO** [comment]
@DavidMachineLearning, for me looks like the plots are stretch and my results are not ok, since my scores are always 1 for all the classifiers. Do you think that there's a problem with it? 
Results: 
{ 'RandomForestClassifier':{
      0:{
         'pred_time':0.007110118865966797,
         'f_test':1.0,
         'train_time':0.03833603858947754,
         'acc_train':1.0,
         'acc_test':1.0,
         'f_train':1.0
      },
      1:{
         'pred_time':0.007297992706298828,
         'f_test':1.0,
         'train_time':0.03605389595031738,
         'acc_train':1.0,
         'acc_test':1.0,
         'f_train':1.0
      },
      2:{
         'pred_time':0.007183074951171875,
         'f_test':1.0,
         'train_time':0.10063600540161133,
         'acc_train':1.0,
         'acc_test':1.0,
         'f_train':1.0
      }
   },
   'GaussianNB':{
      0:{
         'pred_time':0.01777195930480957,
         'f_test':1.0,
         'train_time':0.008568048477172852,
         'acc_train':1.0,
         'acc_test':1.0,
         'f_train':1.0
      },
      1:{
         'pred_time':0.012537956237792969,
         'f_test':1.0,
         'train_time':0.010205984115600586,
         'acc_train':1.0,
         'acc_test':1.0,
         'f_train':1.0
      },
      2:{
         'pred_time':0.011970043182373047,
         'f_test':1.0,
         'train_time':0.10333013534545898,
         'acc_train':1.0,
         'acc_test':1.0,
         'f_train':1.0
      }
   },
   'DecisionTreeClassifier':{
      0:{
         'pred_time':0.005405902862548828,
         'f_test':1.0,
         'train_time':0.0017800331115722656,
         'acc_train':1.0,
         'acc_test':1.0,
         'f_train':1.0
      },
      1:{
         'pred_time':0.0047490596771240234,
         'f_test':1.0,
         'train_time':0.0030469894409179688,
         'acc_train':1.0,
         'acc_test':1.0,
         'f_train':1.0
      },
      2:{
         'pred_time':0.008773088455200195,
         'f_test':1.0,
         'train_time':0.03356003761291504,
         'acc_train':1.0,
         'acc_test':1.0,
         'f_train':1.0
      }
   }
}

**Comment by josiasMO** [comment]
Thanks @fabio-reale  and @DavidMachineLearning. 
I found the problem. I wasn't doing the one-hot encode properly. I'm truly sorry for thinking that the problem was with my plot. 
Again, thanks a lot for the help.

**Comment by pedronovaes** [comment]
Another solution to this problem is replacing the _pl.legend_ to _fig.legend_ and adjusting the _bbox_to_anchor_ to (0.5, 1.05):

```python
fig.legend(handles = patches, bbox_to_anchor = (0.5, 1.05), \ 
           loc = 'upper center', borderaxespad = 0, ncol = 3, fontsize = 'x-large'
```

**Comment by jo4x962k7JL** [comment]
For people who want the same plot as before, you could try this:
1. Adjust figsize from (11, 7) to (16, 12)
2. Adjust  bbox_to_anchor position from (-.80, 2.53) to (-.80, 2.40)
3. Adjust pl.suptitle position from y=1.10 to y=0.99
4. Delete pl.tight_layout(), this is the most important

```python
    # Create figure
    #fig, ax = pl.subplots(2, 3, figsize = (11,7))
    fig, ax = pl.subplots(2, 3, figsize = (16, 12))
    
    #pl.legend(handles = patches, bbox_to_anchor = (-.80, 2.53), \
    pl.legend(handles = patches, bbox_to_anchor = (-.80, 2.40), \
    
    # Aesthetics
    #pl.suptitle("Performance Metrics for Three Supervised Learning Models", fontsize = 16, y = 1.10)
    pl.suptitle("Performance Metrics for Three Supervised Learning Models", fontsize = 16, y = 0.99)
    #pl.tight_layout()
```

<img width="774" alt="vsplot" src="https://user-images.githubusercontent.com/26728779/46251565-8121e780-c40a-11e8-9d72-a26b3b7a43bf.png">
