### ISSUE TITLE
wrong sklearn import library in finding_donors ipynb fie

### ISSUE THREAD

**Issue by BV-Pradeep** [udacity/machine-learning#390]
machine-learning/projects/finding_donors/finding_donors.ipynb file has value error due to wrong addressing of sklearn library. 
The line
`from sklearn.cross_validation import train_test_split`

will generate error due to cross_validation library has been down graded it was replaced with model_selection library.  The screen shots are attched below with error and its correction.
![Screenshot from 2019-07-05 15-08-06](https://user-images.githubusercontent.com/16688720/60713472-d1e4e480-9f36-11e9-825e-a4f5af8a33e9.png)
![Screenshot from 2019-07-05 15-08-37](https://user-images.githubusercontent.com/16688720/60713475-d1e4e480-9f36-11e9-9c80-d0fe54fe8d3a.png)

**Comment by Tejaswgupta** [comment]
try this:
`from sklearn.model_selection import train_test_split `

**Comment by Ashishkumarpanda** [comment]
Cross validation is not used anymore
Try
From sklearn.model_selection import train_test_split

**Comment by ronny-udacity** [comment]
Starting from sklearn v0.20, the package `from sklearn.cross_validation` is now deprecated. If you're using sklearn's newer version, please change this line of code:
-  from: `from sklearn.cross_validation import train_test_split` 
- to: `from sklearn.model_selection import train_test_split`.
