### ISSUE TITLE
Converting the code from Python2 to Python3

### ISSUE THREAD

**Issue by Dawny33** [udacity/machine-learning#46]
As the scientific libraries of Python are slowly stopping the support for Python2 (including Jupyter), maybe it'd be a good idea if we have our code in Python3 rather than Python2.

**Comment by flyinactor91** [comment]
Audacity currently only supports Python 2.7 site-wide. However, this would be a good idea.

I've done this already with the Intro to Machine Learning course back when I was taking the Data Analyst Nano Degree, so I'll be doing it here again as I work through the courses.

https://github.com/flyinactor91/ud120-projects

**Comment by scasasso** [comment]
No news on this one?
It should be high priority

**Comment by AryanJ-NYC** [comment]
@jared-weed Will Udacity's MLND support Python3+ any time soon?

**Comment by Ian-Dzindo01** [comment]
Thanks a lot for sending the link to the python 3  Intro to machine learning course files!

**Comment by Harsh-Joshi-web** [comment]
> Udacity currently only supports Python 2.7 site-wide. However, this would be a good idea.
> 
> I've done this already with the Intro to Machine Learning course back when I was taking the Data Analyst Nano Degree, so I'll be doing it here again as I work through the courses.
> 
> https://github.com/flyinactor91/ud120-projects

Thanks a lot man
