### ISSUE TITLE
Error in tester code for robot motion planning

### ISSUE THREAD

**Issue by lmurtinho** [udacity/machine-learning#49]
I think there's an error in the tester for the provided capstone project (robot motion planning). [Line 105](https://github.com/udacity/machine-learning/blob/99d90ce9250683925fff4308dfc565925b12dd32/projects/capstone/robot_motion_planning/tester.py#L105) (checking if the robot has reached its goal) reads:

`if robot_pos['location'][0] in goal_bounds and robot_pos['location'][1] in goal_bounds:`

Which means position (6, 6) will evaluate to True even if the goal is (6, 7), because both elements in the location tuple are found in the goal_bounds tuple. I believe the line should be simply:

`if robot_pos['location'] == goal_bounds:`

Is it alright if I test this and make a pull request to fix the issue?

**Comment by xushiyan** [comment]
Goal cell consists of 4 cells in the center (5,5),(5,6),(6,5),(6,6) (0-based) 
Therefore it needs bound checking.

**Comment by lmurtinho** [comment]
Oh, I misunderstood the code then. I thought the goal was a single cell, not the 4 cells in the center.
