### ISSUE TITLE
Load Titanic_Survival_Exploration.ipynb failed

### ISSUE THREAD

**Issue by WillAn10** [udacity/machine-learning#59]
When I open this file by command "jupyter notebook Titanic_Survival_Exploration.ipynb", the web page alerts that:

Error loading notebook
Unreadable Notebook: /Users/Documents/WORK/project0_titanic/Titanic_Survival_Exploration.ipynb NotJSONError('Notebook does not appear to be JSON: u\'\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang="e...',)

Could you please help me fix this problem?
Thanks!

**Comment by jared-weed** [comment]
Try instead using `ipython notebook Titanic_Survival_Exploration.ipynb`

**Comment by fabriciocarboni** [comment]
Hi,

I'm running into the same problem. I've tried you mentioned but still the same error.

Tried both command no success,

Any alternative?

Thanks

**Comment by ajfra** [comment]
Same problem as Fabricio. Other people experienced this issues, but I don't see anywhere here what the solution is.

Help, please?

Thanks.
