### ISSUE TITLE
Project 3: function rs.cluster_results(...) legend mislabelled

### ISSUE THREAD

**Issue by omoju** [udacity/machine-learning#60]
The label on the clusters do not correspond to the labels in the legend. For example on the scatterplot, cluster 1 is colored **red** while it is labelled **yellow** in the legend.

![kmeansclustermislabel](https://cloud.githubusercontent.com/assets/1815882/17192824/0b4cfdb4-5405-11e6-94f6-79d836f9e763.png)

**Comment by jared-weed** [comment]
What are the conditions for this occurring? It seems that the labels are entirely mismatched. On my own version of this, the label mismatch you show here does not occur.

**Comment by omoju** [comment]
Went back through my code and removed a function I created. Something how am storing my data must have caused it.

It works fine now
![kmeansclustermislabel](https://cloud.githubusercontent.com/assets/1815882/17195745/a403fd82-5414-11e6-96f3-9f2333c6dd53.png)
