### ISSUE TITLE
Error initializing GUI objects;

### ISSUE THREAD

**Issue by duanweikang** [udacity/machine-learning#81]
For smartcab projects, I have encountered an error on initialize GUI.

Simulator.__init__(): Error initializing GUI objects; display disabled.
error: File is not a Windows BMP file
Simulator.run(): Trial 0

Pygame and libpng is successfully installed.

**Comment by louiswarp** [comment]
I have the same issue, have you been able to fix it ?

**Comment by adamwlev** [comment]
The path that contains the scripts was changed. If you put the images directory inside the smartcab directory, everything works. Kind of amazing this issue was closed without an explanation and that this basic of an issue exists?
